import { requireSuperAdmin } from '@/lib/auth-guards'
import { AIFindingsBoard } from '@/components/ai/ai-findings-board'

export default async function SecurityFindingsPage() {
  await requireSuperAdmin()

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-semibold text-gray-900 dark:text-gray-100">AI Security Findings</h1>
        <p className="mt-2 text-sm text-gray-600 dark:text-gray-300">
          Centralized vulnerability findings generated by the AI governance assistant.
        </p>
      </div>

      <AIFindingsBoard title="AI Security Findings (Global)" />
    </div>
  )
}
