import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { createAdminSupabaseClient } from '@/lib/supabase'
import logAudit from '@/lib/audit'
import type { UserRole } from '@/types'

interface ProfileRow {
  role: UserRole
  school_id: string | null
}

interface CreateTicketBody {
  sessionId: string
  caseId: string
  title: string
  route: string
  objective: string
  expectedResult: string
  priority: 'high' | 'medium' | 'low'
}

async function resolveActor(request: NextRequest) {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

  if (!supabaseUrl || !anonKey) {
    return { error: 'Server configuration error', status: 500 as const }
  }

  const authHeader = request.headers.get('authorization')
  const token = authHeader?.replace('Bearer ', '')

  if (!token) {
    return { error: 'Authorization header required', status: 401 as const }
  }

  const anonClient = createClient(supabaseUrl, anonKey)
  const {
    data: { user },
    error: authError,
  } = await anonClient.auth.getUser(token)

  if (authError || !user) {
    return { error: 'Invalid or expired token', status: 401 as const }
  }

  const adminClient = createAdminSupabaseClient()
  const { data: profile, error: profileError } = await adminClient
    .from('user_profiles')
    .select('role, school_id')
    .eq('user_id', user.id)
    .single()

  if (profileError || !profile) {
    return { error: 'Unable to verify user role', status: 403 as const }
  }

  return { user, adminClient, profile: profile as ProfileRow }
}

export async function GET(request: NextRequest) {
  try {
    const actor = await resolveActor(request)

    if ('error' in actor) {
      return NextResponse.json({ error: actor.error }, { status: actor.status })
    }

    const { user, adminClient, profile } = actor

    let query = (adminClient as any)
      .from('ai_regression_tickets')
      .select(`
        id,
        session_id,
        test_case_id,
        created_by,
        title,
        description,
        priority,
        status,
        created_at,
        ai_sessions!inner(actor_user_id, school_id)
      `)
      .order('created_at', { ascending: false })
      .limit(100)

    if (profile.role === 'super_admin') {
      // full view
    } else if (profile.role === 'school_admin') {
      query = query.eq('ai_sessions.school_id', profile.school_id)
    } else {
      query = query.eq('ai_sessions.actor_user_id', user.id)
    }

    const { data, error } = await query
    if (error) {
      console.error('Error loading regression tickets:', error)
      return NextResponse.json({ error: 'Failed to load regression tickets' }, { status: 500 })
    }

    return NextResponse.json({ success: true, tickets: data || [] }, { status: 200 })
  } catch (error) {
    console.error('Error in AI test-cases GET:', error)
    return NextResponse.json({ error: 'Failed to load regression tickets' }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const actor = await resolveActor(request)

    if ('error' in actor) {
      return NextResponse.json({ error: actor.error }, { status: actor.status })
    }

    const { user, adminClient, profile } = actor
    const body = (await request.json()) as CreateTicketBody

    if (!body.sessionId || !body.caseId || !body.title || !body.route || !body.objective || !body.expectedResult) {
      return NextResponse.json({ error: 'Invalid ticket payload' }, { status: 400 })
    }

    const { data: testCase, error: testCaseError } = await (adminClient as any)
      .from('ai_test_cases')
      .select('id, session_id, role, route, objective, expected_result, priority, ai_sessions!inner(actor_user_id, school_id)')
      .eq('id', body.caseId)
      .eq('session_id', body.sessionId)
      .single()

    if (testCaseError || !testCase) {
      return NextResponse.json({ error: 'Test case not found' }, { status: 404 })
    }

    const ownerUserId = testCase.ai_sessions?.actor_user_id as string | undefined
    const ownerSchoolId = testCase.ai_sessions?.school_id as string | undefined

    const canCreate =
      profile.role === 'super_admin' ||
      (profile.role === 'school_admin' && ownerSchoolId === profile.school_id) ||
      ownerUserId === user.id

    if (!canCreate) {
      return NextResponse.json({ error: 'Not authorized to create ticket for this test case' }, { status: 403 })
    }

    const description = [
      `Route: ${body.route}`,
      `Objective: ${body.objective}`,
      `Expected Result: ${body.expectedResult}`,
      `Generated By: AI test plan`,
    ].join('\n')

    const { data: ticket, error: ticketError } = await (adminClient as any)
      .from('ai_regression_tickets')
      .insert({
        session_id: body.sessionId,
        test_case_id: body.caseId,
        created_by: user.id,
        title: body.title,
        description,
        priority: body.priority,
        status: 'open',
      })
      .select('id')
      .single()

    if (ticketError) {
      if (ticketError.code === '23505') {
        return NextResponse.json({ error: 'A regression ticket already exists for this test case' }, { status: 409 })
      }
      console.error('Error creating regression ticket:', ticketError)
      return NextResponse.json({ error: 'Failed to create regression ticket' }, { status: 500 })
    }

    await (adminClient as any).from('ai_actions').insert({
      session_id: body.sessionId,
      action_name: 'ai_regression_ticket_created',
      action_payload: {
        test_case_id: body.caseId,
        ticket_id: ticket.id,
        priority: body.priority,
      },
      outcome: 'success',
    })

    await logAudit(
      adminClient,
      user.id,
      'ai_regression_ticket_created',
      'ai_test_case',
      body.caseId,
      {
        session_id: body.sessionId,
        ticket_id: ticket.id,
        actor_role: profile.role,
        school_id: profile.school_id,
      }
    )

    return NextResponse.json({ success: true, ticketId: ticket.id }, { status: 200 })
  } catch (error) {
    console.error('Error in AI test-cases POST:', error)
    return NextResponse.json({ error: 'Failed to create regression ticket' }, { status: 500 })
  }
}
